### ISSUE TITLE
Analyze repo and create copilot files

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#3358]
We'll assign this issue to Copilot to give it an opportunity to onboard itself to the project.

Let's make sure Copilot knows how to work effectively in this repository 🤝 .  This includes ensuring, for each area of the codebase, that:

1. Copilot is able to successfully lint, build and test the code.
2. Copilot understands the existing architecture and coding style.
3. Copilot is given access to the tools and context needed to productively collaborate.

To achieve this, we will make changes in the following:

:gear: Update `.github/workflows/copilot-setup-steps.yaml` to include GitHub Actions steps needed to configure the environment that Copilot will work within.  The steps that Copilot will use should all be part of a single `copilot-setup-steps` job.  If other CI or deployment workflows exist, their environment configuration setup steps can be reused here, but only include steps needed to configure the environment for Copilot.  If not, the tools needed by other build scripts/docs (Makefile, README, package.json, etc.) should be included into `copilot-setup-steps.yaml` steps.  Include environment configuration that requires downloading tools or setting up access to package managers, since Copilot will be unable to do those itself after the `copilot-setup-steps` are executed due to it's network limitations.

🗒 Update `.github/copilot-instructions.md` with key information learned from exploring the repo that will be useful for Copilot to remember for future issues.  Keep this to <250 words, so ensure that only high value information is recorded.  Include details about code style and specific tools that should be used for development in each area of the codebase.  Check out things like READMEs, CONTRIBUTING docs, PR templates and other sources of information about how to work effectively in the repo.

Lastly, as part of doing this work, Copilot should raise any questions or concerns it has around how best to work in the repository, so that the dev team can answer them and help set up Copilot for success :star:.  If Copilot cannot successfully build or test, and does not believe that its updates to `.github/workflows/copilot-setup-steps.yaml` will enable it to, it should raised those as explicit notes for the dev team.  The PR should also request that the dev team ask @copilot to try out the build and test as a comment on the PR so that Copilot has a chance to try the newly added `.github/workflows/copilot-setup-steps.yaml`.

<details>

Example `.github/copilot-setup-steps.md` file:

```yaml
name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for github/setup-goproxy
      contents: read # for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download Go dependencies
        run: go mod download
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: runtime/package-lock.json
      - name: Install runtime dependencies
        working-directory: ./runtime
        run: npm install
      - name: Azure Login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          client-id: "${{ secrets.AZURE_CLIENT_ID }}"
          tenant-id: "${{ secrets.AIP_AZURE_TENANT_ID }}"
          subscription-id: "${{ secrets.AIP_AZURE_SUBSCRIPTION_ID }}"
```
</details>
